### ISSUE TITLE
Login screen still has bright elements

### ISSUE THREAD

**Issue by cmccandless** [Aloso/exercism-dark#1]
![image](https://user-images.githubusercontent.com/7275238/62466258-eba86000-b75e-11e9-8ac9-7835b23004ed.png)

**Comment by cmccandless** [comment]
Some of that is images that cannot be altered with CSS, but the bottom panel should be fixable.

**Comment by Aloso** [comment]
I inverted the images with white background using `filter: invert(0.9) hue-rotate(180deg)`.

Sadly, this produces a normal dark gray, while the actual background is blueish (`#111A1D`). If I can't figure this out, I might have to switch to a neutral gray for the whole page.

**Comment by Aloso** [comment]
The logos can't be inverted, so this area will stay white.
