### ISSUE TITLE
Hyperlinks in exercise descriptions are still dark on dark

### ISSUE THREAD

**Issue by cmccandless** [Aloso/exercism-dark#4]
Hyperlinks in exercise descriptions should be blue like this:
![image](https://user-images.githubusercontent.com/7275238/62947707-fd1de780-bdb0-11e9-9f36-c0ad5ce09825.png)
*Url: https://exercism.io/tracks/javascript/installation*

But are dark grey:

![image](https://user-images.githubusercontent.com/7275238/62947517-aa443000-bdb0-11e9-892c-ec3d1cec6888.png)
*Url: https://exercism.io/my/solutions/0d379913c7d14787a46cbdb722fa2dc4*

**Browser**

Google Chrome | 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Linux
JavaScript | V8 7.6.303.29

**Comment by Aloso** [comment]
EDIT: I think you have an older version of the theme. Does the bug persist after going to https://userstyles.org/styles/174119/exercism-dark and clicking on "Update"?

**Comment by cmccandless** [comment]
Update resolved the issue!
