### ISSUE TITLE
Cursor and text in mentor "Exercise" search menu is almost unreadable

### ISSUE THREAD

**Issue by HarrisonMc555** [Aloso/exercism-dark#6]
**Describe the bug**
- What's the problem?
  - On the mentor dashboard on the "Solutions you're mentoring" tab, there is a drop-down/text box combination labeled "Exercise". If you type text in there, it is almost the same color as the background and is almost unreadable.

- Did you open the page as a student, a mentor, a maintainer or were you not logged in?
  - A mentor.

**Screenshots**

![image](https://user-images.githubusercontent.com/22666187/66233398-844c5500-e6a8-11e9-9838-d08f9eade161.png)

**Browser**
 - Google Chrome version 77.0.3865.90 (Official Build) (64-bit)
 - macOS version 10.14.6 (18G103)

**Comment by Aloso** [comment]
Thank you for the issue! Sorry for answering so late, I'll look at this issue this week.

**Comment by HarrisonMc555** [comment]
Looks great! Thanks :-)
